/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SendRouteImport } from './routes/send'
import { Route as RankingsRouteImport } from './routes/rankings'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PortfolioRouteImport } from './routes/portfolio'
import { Route as MarketRouteImport } from './routes/market'
import { Route as ExploreRouteImport } from './routes/explore'
import { Route as DropsRouteImport } from './routes/drops'
import { Route as ActivityRouteImport } from './routes/activity'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MarketIdRouteImport } from './routes/market.$id'
import { Route as CollectionSlugRouteImport } from './routes/collection.$slug'
import { Route as AssetIdRouteImport } from './routes/asset.$id'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SendRoute = SendRouteImport.update({
  id: '/send',
  path: '/send',
  getParentRoute: () => rootRouteImport,
} as any)
const RankingsRoute = RankingsRouteImport.update({
  id: '/rankings',
  path: '/rankings',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioRoute = PortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketRoute = MarketRouteImport.update({
  id: '/market',
  path: '/market',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreRoute = ExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => rootRouteImport,
} as any)
const DropsRoute = DropsRouteImport.update({
  id: '/drops',
  path: '/drops',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivityRoute = ActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketIdRoute = MarketIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => MarketRoute,
} as any)
const CollectionSlugRoute = CollectionSlugRouteImport.update({
  id: '/collection/$slug',
  path: '/collection/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AssetIdRoute = AssetIdRouteImport.update({
  id: '/asset/$id',
  path: '/asset/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/drops': typeof DropsRoute
  '/explore': typeof ExploreRoute
  '/market': typeof MarketRouteWithChildren
  '/portfolio': typeof PortfolioRoute
  '/profile': typeof ProfileRoute
  '/rankings': typeof RankingsRoute
  '/send': typeof SendRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/asset/$id': typeof AssetIdRoute
  '/collection/$slug': typeof CollectionSlugRoute
  '/market/$id': typeof MarketIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/drops': typeof DropsRoute
  '/explore': typeof ExploreRoute
  '/market': typeof MarketRouteWithChildren
  '/portfolio': typeof PortfolioRoute
  '/profile': typeof ProfileRoute
  '/rankings': typeof RankingsRoute
  '/send': typeof SendRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/asset/$id': typeof AssetIdRoute
  '/collection/$slug': typeof CollectionSlugRoute
  '/market/$id': typeof MarketIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/drops': typeof DropsRoute
  '/explore': typeof ExploreRoute
  '/market': typeof MarketRouteWithChildren
  '/portfolio': typeof PortfolioRoute
  '/profile': typeof ProfileRoute
  '/rankings': typeof RankingsRoute
  '/send': typeof SendRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/asset/$id': typeof AssetIdRoute
  '/collection/$slug': typeof CollectionSlugRoute
  '/market/$id': typeof MarketIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/activity'
    | '/drops'
    | '/explore'
    | '/market'
    | '/portfolio'
    | '/profile'
    | '/rankings'
    | '/send'
    | '/sitemap.xml'
    | '/asset/$id'
    | '/collection/$slug'
    | '/market/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/activity'
    | '/drops'
    | '/explore'
    | '/market'
    | '/portfolio'
    | '/profile'
    | '/rankings'
    | '/send'
    | '/sitemap.xml'
    | '/asset/$id'
    | '/collection/$slug'
    | '/market/$id'
  id:
    | '__root__'
    | '/'
    | '/activity'
    | '/drops'
    | '/explore'
    | '/market'
    | '/portfolio'
    | '/profile'
    | '/rankings'
    | '/send'
    | '/sitemap.xml'
    | '/asset/$id'
    | '/collection/$slug'
    | '/market/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ActivityRoute: typeof ActivityRoute
  DropsRoute: typeof DropsRoute
  ExploreRoute: typeof ExploreRoute
  MarketRoute: typeof MarketRouteWithChildren
  PortfolioRoute: typeof PortfolioRoute
  ProfileRoute: typeof ProfileRoute
  RankingsRoute: typeof RankingsRoute
  SendRoute: typeof SendRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  AssetIdRoute: typeof AssetIdRoute
  CollectionSlugRoute: typeof CollectionSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/send': {
      id: '/send'
      path: '/send'
      fullPath: '/send'
      preLoaderRoute: typeof SendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rankings': {
      id: '/rankings'
      path: '/rankings'
      fullPath: '/rankings'
      preLoaderRoute: typeof RankingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio': {
      id: '/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof PortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/market': {
      id: '/market'
      path: '/market'
      fullPath: '/market'
      preLoaderRoute: typeof MarketRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore': {
      id: '/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof ExploreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/drops': {
      id: '/drops'
      path: '/drops'
      fullPath: '/drops'
      preLoaderRoute: typeof DropsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activity': {
      id: '/activity'
      path: '/activity'
      fullPath: '/activity'
      preLoaderRoute: typeof ActivityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/market/$id': {
      id: '/market/$id'
      path: '/$id'
      fullPath: '/market/$id'
      preLoaderRoute: typeof MarketIdRouteImport
      parentRoute: typeof MarketRoute
    }
    '/collection/$slug': {
      id: '/collection/$slug'
      path: '/collection/$slug'
      fullPath: '/collection/$slug'
      preLoaderRoute: typeof CollectionSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/asset/$id': {
      id: '/asset/$id'
      path: '/asset/$id'
      fullPath: '/asset/$id'
      preLoaderRoute: typeof AssetIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface MarketRouteChildren {
  MarketIdRoute: typeof MarketIdRoute
}

const MarketRouteChildren: MarketRouteChildren = {
  MarketIdRoute: MarketIdRoute,
}

const MarketRouteWithChildren =
  MarketRoute._addFileChildren(MarketRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ActivityRoute: ActivityRoute,
  DropsRoute: DropsRoute,
  ExploreRoute: ExploreRoute,
  MarketRoute: MarketRouteWithChildren,
  PortfolioRoute: PortfolioRoute,
  ProfileRoute: ProfileRoute,
  RankingsRoute: RankingsRoute,
  SendRoute: SendRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  AssetIdRoute: AssetIdRoute,
  CollectionSlugRoute: CollectionSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
